; Generated by scripts/prepare-gstreamer.js
!macro NSIS_HOOK_POSTINSTALL
  SetOutPath "$INSTDIR"
  File "C:\Users\lvllaby\Documents\sone\src-tauri\gstreamer-runtime\*.dll"
  
  SetOutPath "$INSTDIR\lib\gstreamer-1.0"
  File "C:\Users\lvllaby\Documents\sone\src-tauri\gstreamer-runtime\lib\gstreamer-1.0\*.dll"
  
  SetOutPath "$INSTDIR\lib\gio\modules"
  File "C:\Users\lvllaby\Documents\sone\src-tauri\gstreamer-runtime\lib\gio\modules\*.dll"
!macroend

!macro NSIS_HOOK_PREUNINSTALL
  Delete "$INSTDIR\*.dll"
  RMDir /r "$INSTDIR\lib"
!macroend
